export const MARCAS_MAQUINARIA = [
  { id: 1, slug: "caterpillar", name: "Caterpillar (CAT)" },
  { id: 2, slug: "komatsu", name: "Komatsu" },
  { id: 3, slug: "john_deere", name: "John Deere" },
  { id: 4, slug: "case", name: "CASE Construction" },
  { id: 5, slug: "jcb", name: "JCB" },
  { id: 6, slug: "volvo", name: "Volvo CE" },
  { id: 7, slug: "bobcat", name: "Bobcat" },
  { id: 8, slug: "sany", name: "Sany" },
  { id: 9, slug: "liugong", name: "LiuGong" },
  { id: 10, slug: "develon_doosan", name: "Develon (Doosan)" },
  { id: 11, slug: "hitachi", name: "Hitachi" },
  { id: 12, slug: "new_holland", name: "New Holland" },
  { id: 13, slug: "kobelco", name: "Kobelco" },
  { id: 14, slug: "hyundai", name: "Hyundai CE" },
  { id: 15, slug: "xcmg", name: "XCMG" },
  { id: 16, slug: "terex", name: "Terex" },
  { id: 17, slug: "liebherr", name: "Liebherr" },
  { id: 18, slug: "wacker_neuson", name: "Wacker Neuson" },
  { id: 19, slug: "shantui", name: "Shantui" },
  { id: 20, slug: "sdlg", name: "SDLG" },
];
