import { StyleSheet } from "react-native";
import { DesignTokens } from "../../../../styles/designTokens";

export default StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    backgroundColor: DesignTokens.colors.background.secondary,
    borderRadius: DesignTokens.borderRadius.lg,
    padding: 0,
    alignItems: "stretch",
    ...DesignTokens.shadows.lg,
    position: "relative",
  },
  header: {
    backgroundColor: DesignTokens.colors.executive.primary,
    borderTopLeftRadius: DesignTokens.borderRadius.lg,
    borderTopRightRadius: DesignTokens.borderRadius.lg,
    paddingTop: DesignTokens.spacing["3xl"],
    paddingBottom: DesignTokens.spacing.lg,
    paddingHorizontal: DesignTokens.spacing.lg,
    alignItems: "center",
  },
  title: {
    fontSize: DesignTokens.typography.fontSize["3xl"],
    fontWeight: DesignTokens.typography.fontWeight.bold as any,
    color: DesignTokens.colors.background.primary,
    textAlign: "center",
  },
  subtitle: {
    fontSize: DesignTokens.typography.fontSize.lg,
    color: DesignTokens.colors.primary[200],
    textAlign: "center",
    marginTop: DesignTokens.spacing.xs,
  },
  sectionTitle: {
    fontSize: DesignTokens.typography.fontSize.xl,
    fontWeight: DesignTokens.typography.fontWeight.medium as any,
    color: DesignTokens.colors.neutral[700],
    marginTop: DesignTokens.spacing["2xl"],
    marginLeft: DesignTokens.spacing.lg,
    marginBottom: DesignTokens.spacing.sm,
  },
  summaryBox: {
    backgroundColor: DesignTokens.colors.background.primary,
    borderRadius: DesignTokens.borderRadius.md,
    borderWidth: 1,
    borderColor: DesignTokens.colors.neutral[300],
    marginHorizontal: DesignTokens.spacing.lg,
    padding: DesignTokens.spacing.lg,
    marginBottom: DesignTokens.spacing.lg,
    maxHeight: "50%",
    overflow: "hidden",
  },
  summaryLabel: {
    fontWeight: DesignTokens.typography.fontWeight.semibold as any,
    fontSize: DesignTokens.typography.fontSize.base,
    color: DesignTokens.colors.neutral[900],
    marginTop: DesignTokens.spacing.sm,
  },
  summaryValue: {
    fontSize: DesignTokens.typography.fontSize.sm,
    color: DesignTokens.colors.neutral[500],
    marginBottom: DesignTokens.spacing.xs / 2,
  },
  checkbox: {
    borderColor: DesignTokens.colors.neutral[400],
  },
  checkboxContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: DesignTokens.spacing.lg,
    marginBottom: DesignTokens.spacing.lg,
  },
  checkboxLabel: {
    fontSize: DesignTokens.typography.fontSize.sm,
    color: DesignTokens.colors.neutral[700],
    marginLeft: DesignTokens.spacing.sm,
    flex: 1,
  },
  buttonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: DesignTokens.spacing.lg,
    marginBottom: DesignTokens.spacing.lg,
  },
  editButton: {
    flex: 1,
    backgroundColor: DesignTokens.colors.background.primary,
    borderColor: DesignTokens.colors.executive.primary,
    borderWidth: 2,
    borderRadius: DesignTokens.borderRadius.base,
    paddingVertical: DesignTokens.spacing.md,
    marginRight: DesignTokens.spacing.sm,
    alignItems: "center",
  },
  editButtonText: {
    color: DesignTokens.colors.executive.primary,
    fontWeight: DesignTokens.typography.fontWeight.bold as any,
    fontSize: DesignTokens.typography.fontSize.lg,
  },
  confirmButton: {
    flex: 1,
    backgroundColor: DesignTokens.colors.executive.primary,
    borderRadius: DesignTokens.borderRadius.base,
    paddingVertical: DesignTokens.spacing.md,
    marginLeft: DesignTokens.spacing.sm,
    alignItems: "center",
  },
  confirmButtonDisabled: {
    backgroundColor: DesignTokens.colors.neutral[400],
  },
  confirmButtonText: {
    color: DesignTokens.colors.background.primary,
    fontWeight: DesignTokens.typography.fontWeight.bold as any,
    fontSize: DesignTokens.typography.fontSize.lg,
  },
  closeButton: {
    position: "absolute",
    top: DesignTokens.spacing.sm,
    right: DesignTokens.spacing.sm,
    zIndex: 2,
    padding: DesignTokens.spacing.xs,
  },
});
